# Generated by Django 2.1 on 2020-07-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='contact_no',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100, null=True),
        ),
    ]
