# Generated by Django 2.2.13 on 2020-07-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentledger',
            name='client_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Supplier'), (1, 'SHOP')]),
        ),
        migrations.AlterField(
            model_name='paymentledger',
            name='payment_mode',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Cash'), (1, 'Cheque'), (2, 'NEFT')], default=0),
        ),
    ]
