# Generated by Django 2.1 on 2020-07-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial_squashed_0003_product_tax_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinwarddetails',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='stockinwarddetails',
            name='po_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stockinwarddetails',
            name='stock_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stockinwarddetails',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
