# Generated by Django 2.2.13 on 2020-07-18 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0002_auto_20200702_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinwarddetails',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Add Stock'), (1, 'Return to Supplier'), (2, 'Return from Shop')], default=0),
        ),
        migrations.AlterField(
            model_name='stockinwarddetails',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogue.Product'),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=200)),
                ('contact_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='Mobile Number')),
                ('email', models.EmailField(blank=True, default='', max_length=100, null=True)),
                ('address', models.TextField(max_length=1000)),
                ('gst', models.CharField(blank=True, max_length=200, null=True, verbose_name='GST Number')),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_by', models.ForeignKey(on_delete=False, related_name='supplier_created_on', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=False, related_name='supplier_updated_on', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='stockinwarddetails',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalogue.Supplier'),
        ),
    ]
